name: Postar Boa Noite

on:
  schedule:
    - cron: '0 23 * * *'   # 20:00 da noite em Brasília
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar Boa Noite
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🌙 Boa noite, família! ⭐🌠

            Antes de dormir, dá uma olhadinha nas promoções que ainda estão valendo hoje!

            🛒💰 As ofertas diárias foram incríveis e amanhã vem mais!

            Qual foi a melhor promoção que você viu hoje?

            😴✨ Durma bem e sonhe com economias!
